# Generated by Django 5.2 on 2025-10-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapefile_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapefile',
            name='geojson_data',
            field=models.JSONField(default=dict),
        ),
    ]
