# Generated by Django 5.2 on 2025-10-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shapefile_app', '0002_alter_shapefile_geojson_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapefile',
            name='geojson_data_processed',
            field=models.JSONField(blank=True, null=True, verbose_name='Source Polygon intersected with hist and split (multi) polygon geometry'),
        ),
    ]
